[package]
name = "windows-audio-test-tone"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
] }

[target.'cfg(target_os = "windows")'.dev-dependencies]
pw-graph-backend = { path = "../pw-graph-backend" }
