[package]
name = "pw-graph-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[[bin]]
name = "qpwgraph-rs"
path = "src/main.rs"

[features]
default = ["pipewire", "alsa", "tray", "relay"]
pipewire = ["pw-graph-backend/pipewire"]
alsa = ["pw-graph-alsamidi/alsa"]
relay = ["pw-graph-backend/relay", "pipewire"]
tray = ["dep:ksni"]

[dependencies]
slint.workspace = true
slint-node-editor.workspace = true
rfd.workspace = true
ksni = { version = "0.3.6", default-features = false, features = ["blocking", "async-io"], optional = true }
pw-graph-backend = { path = "../pw-graph-backend" }
pw-graph-alsamidi = { path = "../pw-graph-alsamidi", default-features = false }
pw-graph-command = { path = "../pw-graph-command" }
pw-graph-config = { path = "../pw-graph-config" }
pw-graph-core = { path = "../pw-graph-core" }
pw-graph-effects = { path = "../pw-graph-effects" }
pw-graph-i18n = { path = "../pw-graph-i18n" }
pw-graph-patchbay = { path = "../pw-graph-patchbay" }
pw-graph-ui = { path = "../pw-graph-ui" }

[build-dependencies]
slint-build.workspace = true
